---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by burei.
--- DateTime: 22/03/2022 22:59
---
Spawn_Vehicle_1 = SPAWN:New('Spawn Vehicle 1')
Spawn_Group_1 = Spawn_Vehicle_1:Spawn()
